// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPlcHIjWDAk-JgEWHoJXwcrv3NXs0ZXU',
    appId: '1:764247132364:web:e547739f3b3dd080c49a69',
    messagingSenderId: '764247132364',
    projectId: 'chat-app-8352e',
    authDomain: 'chat-app-8352e.firebaseapp.com',
    storageBucket: 'chat-app-8352e.appspot.com',
    measurementId: 'G-ZGKBKR33FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LA1nJ-9bVbZrghKHN4iw5Dx0t4Zf5Dk',
    appId: '1:764247132364:android:2e679e72c360e72fc49a69',
    messagingSenderId: '764247132364',
    projectId: 'chat-app-8352e',
    storageBucket: 'chat-app-8352e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6JQX9W7W2yktqsri-m0ZhUVEQf6V484',
    appId: '1:764247132364:ios:659a34cc4f277ad1c49a69',
    messagingSenderId: '764247132364',
    projectId: 'chat-app-8352e',
    storageBucket: 'chat-app-8352e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6JQX9W7W2yktqsri-m0ZhUVEQf6V484',
    appId: '1:764247132364:ios:659a34cc4f277ad1c49a69',
    messagingSenderId: '764247132364',
    projectId: 'chat-app-8352e',
    storageBucket: 'chat-app-8352e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALPlcHIjWDAk-JgEWHoJXwcrv3NXs0ZXU',
    appId: '1:764247132364:web:95f346d6bef36a23c49a69',
    messagingSenderId: '764247132364',
    projectId: 'chat-app-8352e',
    authDomain: 'chat-app-8352e.firebaseapp.com',
    storageBucket: 'chat-app-8352e.appspot.com',
    measurementId: 'G-LPH6Q7FVYS',
  );
}
